config/routes.rb
Rails.application.routes.draw do

  root 'goals#index'

  resources :goals do
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  @@values = Hash.new()
  #@@values[0] = "worthless"
  @@values[0] = "insignificant"
  @@values[1] = "worthwhile"
  @@values[2] = "valuable"
  @@values[3] = "priceless"
  def self.values
    @@values
  end

  @@efforts = Hash.new()
  #@@efforts[0] = "trivial"
  @@efforts[0] = "easy"
  @@efforts[1] = "doable"
  @@efforts[2] = "challenging"
  @@efforts[3] = "grueling"

  def self.efforts
    @@efforts
  end

  @@days = Hash.new()
  #@@days[1] = "a day"
  @@days[7] = "a week"
  @@days[30] = "a month"
  @@days[60] = "2 months"
  @@days[183] = "6 months"
  @@days[365] = "a year"
  @@days[1825] = "5 years"
  #@@days[3650] = "10 years"
  #@@days[10950] = "a career"    #TODO 30 years. Depends on age.
  #@@days[18250] = "a lifetime"  #TODO 50 years. Depends on age.

  def self.days
    @@days
  end

  validates :text, presence: true #TODO Check length and attacks.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    #TOOO Need to add date values.
    if @goal.save
      #redirect_to @goal
      redirect_to goals_path
    else
      render 'new'
    end
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def index
    case params[:status]
    when "complete"
      @goals = Goal.where(complete: true)
    when "all"
      @goals = Goal.all
    else
      @goals = Goal.where(complete: false)
    end
    case params[:order]
    when nil, "created"
      @goals = @goals.sort_by(&:created_at).reverse
    when "days"
      @goals = @goals.sort_by(&:days)
    when "value"
      @goals = @goals.sort_by(&:value).reverse
    when "effort"
      @goals = @goals.sort_by(&:effort)
    when "magic"
      @goals = @goals.sort {|a,b| [a.days, b.value, a.effort] <=> [b.days, a.value, b.effort]}
    else
      #TODO Throw an error.
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if params[:complete] == nil
      if @goal.update(goal_params)
        redirect_to @goal
      else
        render 'edit'
      end
    else      
      if @goal.update(complete: params[:complete])
        redirect_to goals_path
      else
        render 'show' #TODO Need to check for errors in show view.
      end      
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_path
  end

  private
  def goal_params
    params.require(:goal).permit(:days, :text, :value, :effort)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
  def days_left(created_at, days)
    return (days.to_i - (DateTime.now - created_at.to_datetime)).round
  end
end

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>
<% if @goal.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@goal.errors.count, "error") %> prohibited
	this article from being saved:</h2>
	<ul>
		<% @goal.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<p>
	<%= f.label "Goal" %>
	<br>
	<%= f.text_field :text %>
</p>

<p>
	<%= f.label "Timeframe" %>
	<br>
	<%= f.select(:days, Goal.days.invert) %>
</p>

<p>
	<%= f.label :value %>
	<br>
	<!-- #TODO Select middle option by default. -->
	<%= f.select(:value, Goal.values.invert) %>
</p>

<p>
	<%= f.label :effort %>
	<br>
	<!-- #TODO Select middle option by default. -->
	<%= f.select(:effort, Goal.efforts.invert) %>
</p>

<p>
	<%= f.submit %>
</p>
<% end %>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<%= render 'form' %>

app/views/goals/index.html.erb
<h1>All Goals</h1>

<ul>
	<li>
		<%= link_to 'Timeframe', goals_path(order: "days", status: params[:status]) %>
	</li>
	<li>
		<%= link_to 'Value', goals_path(order: "value", status: params[:status]) %>
	</li>
	<li>
		<%= link_to 'Effot', goals_path(order: "effort", status: params[:status]) %>
	</li>
	<li>
		<%= link_to 'Created', goals_path(order: "created", status: params[:status]) %>
	</li>
	<li>
		<%= link_to 'Magic', goals_path(order: "magic", status: params[:status]) %>
	</li>
</ul>

<ul>
	<li>
		<%= link_to 'Show Complete', goals_path(order: params[:order], status: "complete") %>
	</li>
	<li>
		<%= link_to 'Show Incomplete', goals_path(order: params[:order], status: "incomplete") %>
	</li>
	<li>
		<%= link_to 'Show All', goals_path(order: params[:order], status: "all") %>
	</li>
</ul>

<ul>
	<% @goals.each do |goal| %>
	<li>
		<%= link_to goal.text + ' - ' + days_left(goal.created_at, goal.days).to_s + 'd ' + goal.value.to_s + 'v ' + goal.effort.to_s + 'e', goal_path(goal) %>
	</li>
	<% end %>
</ul>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form' %>

app/views/goals/show.html.erb
<!-- #TODO make a template for this sentence -->
<p>
	Within <%= Goal.days[@goal.days] %> I will <%= @goal.text %> which will be <%= Goal.values[@goal.value] %>  and <%= Goal.efforts[@goal.effort] %>.
</p>

<ul>
	<li>
		<%= link_to 'Edit', edit_goal_path(@goal) %>
	</li>
	<li>
		<%= link_to 'Delete', goal_path(@goal), method: :delete, data: { confirm: 'Are you sure?' } %>
	</li>
	<li>
		<% if @goal.complete %>
		<%= link_to 'Incomplete', goal_path(@goal, complete: "false"), method: :patch %>
		<% else %>
		<%= link_to 'Complete', goal_path(@goal, complete: "true"), method: :patch %>
		<% end %>
	</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Goals</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<!--
		<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile-1.4.3.min.css" />
		<script src="http://code.jquery.com/mobile/1.4.3/jquery.mobile-1.4.3.min.js"></script>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		-->
		<%= csrf_meta_tags %>
	</head>
	<body>
		<ul>
			<li>
				<a href="<%= goals_path %>">Index</a>
			</li>
			<li>
				<a href="<%= new_goal_path %>">Create</a>
			</li>
		</ul>
		<!--
		<div data-role="page">
		<div data-role="header" data-position="fixed">
		<a href="<%= goals_path %>" class="ui-btn-left ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-home ui-btn-icon-notext"></a>
		<h1>Reacher</h1>
		<a href="<%= new_goal_path %>" class="ui-btn-right ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-right ui-icon-plus ui-btn-icon-notext"></a>
		</div>
		<div data-role="main" class="ui-content">
		-->
		<%= yield %>
		<!--
		</div>
		<div data-role="footer" data-position="fixed">
		<h1>Copyright <%= Time.now.year %> Michael Davies</h1>
		</div>
		</div>
		-->
	</body>
</html>